package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	_ "github.com/go-sql-driver/mysql"
)

//a port
const portPub string = ":8080"

//yueque URL
var yqURL string = "https://www.yuque.com/"

//obtain the message from yueque by webhook
//then save in mysql
//then enter next
func getMes(w http.ResponseWriter, r *http.Request) {
	data, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Fatalf("ioutil error:%s", err)
	}

	autoGenerated := &AutoGenerated{}

	err = json.Unmarshal(data, &autoGenerated)
	if err != nil {
		log.Fatalf("unmarshal error:%s", err)
	}

	fmt.Println("---------new--------")
	fmt.Println(autoGenerated.Data.Title)
	fmt.Println(autoGenerated.Data.User.Name)

	stra := yqURL + autoGenerated.Data.Path
	fmt.Println(stra)

	title := autoGenerated.Data.Title
	name := autoGenerated.Data.User.Name
	path := stra

	db, err := sql.Open("mysql", "root:123456@tcp(127.0.0.1:3306)/YQ")
	if err != nil {
		log.Fatalf("sql.Open error: %s\n", err)
	}

	stmt, err := db.Prepare("INSERT user_info SET title=?,name=?,path=?")
	if err != nil {
		log.Fatalf("db.Prepare error: %s\n", err)
	}

	_, err = stmt.Exec(title, name, path)
	if err != nil {
		log.Fatalf("stmt.Exec error: %s\n", err)
	}

	text := title + "\n" + name + "\n" + path + "\n"
	startBot(text)
}
